### PR TITLE
[spdlog]: link it in private

### PR DESCRIPTION
**Pull request by Milerius**
don't force usage of a specific spdlog version to end-users

### CODE REVIEW

**Comment by Milerius** [comment]
another solution is to let us use find_package for spdlog instead of using the one from your fetch content

**Comment by OlivierLDff** [comment]
Why is it problem for you? What is your use case?
I put in in public due to:
https://github.com/OlivierLDff/Qaterial/blob/e4a4cc7fd1055c050a072c777e088971b870732e/include/Qaterial/Logger.hpp#L13-L14

Because there is spdlog linked in public headers, the user expect a public spdlog link.

**Comment by Milerius** [comment]
> Why is it problem for you? What is your use case?
> I put in in public due to:
> https://github.com/OlivierLDff/Qaterial/blob/e4a4cc7fd1055c050a072c777e088971b870732e/include/Qaterial/Logger.hpp#L13-L14
> 
> Because there is spdlog linked in public headers, the user expect a public spdlog link.

opsecs issue mostly we would like to use our fork of spdlog through find_package and not use one through fetch_content.

In my application i use spdlog installed through safe conan/vcpkg but it's conflicting with yours due to the public linking

**Comment by OlivierLDff** [comment]
https://github.com/OlivierLDff/Qaterial/blob/e4a4cc7fd1055c050a072c777e088971b870732e/cmake/Dependencies.cmake#L19-L20

Before fetching Qaterial you should set a variable in the cache `SPDLOG_REPOSITORY` and make it point to your fork. This can also be a local url

**Comment by Milerius** [comment]
is it possible to disable the whole logger somehow ?

**Comment by OlivierLDff** [comment]
Yes i could add a CMake option for that.
Like `QATERIAL_ENABLE_LOGGER`

Why `if(NOT spdlog_FOUND)` solution isn't ok for you?

**Comment by Milerius** [comment]
> Yes i could add a CMake option for that.
> Like `QATERIAL_ENABLE_LOGGER`
> 
> Why `if(NOT spdlog_FOUND)` solution isn't ok for you?

I think you approach is better with the find_package, i even think that we should start packaging Qaterial, let's say for VCPKG from the CMake point of view is not that hard but i wonder about QOlm and the ressources in general, should i open a separate issue for that ?

**Comment by OlivierLDff** [comment]
Yes why not let's open an issue about that. But I won't have time to support it myself. So feel free to pr.
What are the requirement? QOlm should maybe be packaged first?

I want to keep FetchContent as default dependency manager since it is working out of the box and it is very easy to cross compile with it.

**Comment by Milerius** [comment]
> Yes why not let's open an issue about that. But I won't have time to support it myself. So feel free to pr.
> What are the requirement? QOlm should maybe be packaged first?
> 
> I want to keep FetchContent as default dependency manager since it is working out of the box and it is very easy to cross compile with it.

Yes for that we can have an option in all your CMake Project such as `PREFER_FIND_PACKAGE` if you know what i mean, but the best thing is, we can also only package QAterial, it's will work with the fetch_content approach, just use find_package for spdlog and that's it, i will study a bit

**Comment by OlivierLDff** [comment]
Everything is supposed to be in `qrc:/Qaterial` so it's really only Qaterial.lib + headers.
So introducing a `QATERIAL_PREFER_FIND_PACKAGE` would be solution?

**Comment by Milerius** [comment]
Absolutely @OlivierLDff i will open the issue etc.

> Everything is supposed to be in `qrc:/Qaterial` so it's really only Qaterial.lib + headers.
> So introducing a `QATERIAL_PREFER_FIND_PACKAGE` would be solution?

> What benefit the package system will provide? I never used vcpkg, and each time i tried to use package manager i was struggeling with wrong version, incompatibilies, etc...

vcpkg is very strong recently, start supporting versionning, cross-platform, and works well with secure-reviewed fork.

There is my approach:

- Maintains a set of custom ports: https://github.com/KomodoPlatform/vcpkg-custom-ports/tree/main/ports
- Use the new manifest approach https://vcpkg.readthedocs.io/en/latest/specifications/manifests/
- Or a [response file](https://github.com/KomodoPlatform/atomicDEX-Desktop/blob/dev/.github/workflows/osx_response_file.txt)
- Normally with `manifests` the good thing is that it's automatically updating to the last version that are described in your custom ports folder.

If you want my overall overview, vcpkg is really good if you mind security for your users and enjoy clean fork.

forget about conan or others, they are to hard to maintains

**Comment by OlivierLDff** [comment]
Ok i understand but i still don't see what the problem is with qrc. All qml files are embedded into the library Qaterial, so you just need to have Qaterial.lib deployed. Why do you want to deploy qrc files?

**Pull request closed without merging**
